Selective ci
linear-b/gitstream pull request #305
Opened 2023-09-04 11:06 UTC by PavelLinearB

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1993POnw6wEwe0fUhMNUOUQwQz6pN3ilk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=RD0s9tK)

![image](https://github.com/linear-b/gitstream/assets/129676672/eb349b29-1db7-43eb-8fd4-d8fffe491be5)

![image](https://github.com/linear-b/gitstream/assets/129676672/3ec061cb-d692-465a-83f9-220c6cbb2d36)

![image](https://github.com/linear-b/gitstream/assets/129676672/64e057fb-d85b-44e4-bb7c-e84e9b1f61fa)

2023-09-04 11:20 UTC, vim-zz requested changes

2023-09-04 11:20 UTC, vim-zz commented on docs/execution-model.md
> +		  reviewers: {{ repo | codeExperts(gt=10) }}
the example use uneven spaces for indendation, use 2 spaces for every indentation level

2023-09-04 11:20 UTC, vim-zz commented on docs/execution-model.md
> +    After each commit **or** after adding the label.
some description of what will happen once you use the `on: commit` compared to not using it, would be very helpful.

2023-09-04 11:20 UTC, vim-zz commented on docs/execution-model.md
> +Explicit triggers can be used at the file level, specific to each automation separately, or a combination of the two. In case triggers are listed at the file level **and** specific automation, the au
Worth mentioing the fact triggers are set per automation block, as either default (implicit), union of in-autoamtion + in-cm (explicit)

2023-09-05 07:18 UTC, PavelLinearB commented
#jit_bypass_commit

2023-09-05 08:32 UTC, vim-zz requested changes

2023-09-05 14:06 UTC, vim-zz approved these changes

2023-09-05 14:51 UTC, merged