added chip icon and wand, moved main askAI page
linear-b/gitstream pull request #601
Opened 2024-10-15 12:48 UTC by PavelLinearB

2024-10-15 12:52 UTC, MishaKav approved these changes
👍

2024-11-11 07:06 UTC, vim-zz approved these changes

2024-12-23 10:24 UTC, MishaKav requested changes

2024-12-23 10:24 UTC, MishaKav commented on docs/downloads/automation-library/integrations/askAI/askAI_improve.cm
> +              Focus only on the modified code and provide specific, actionable recommendations.", env.OPEN_AI_TOKEN) | encode }}
please remove the `encode` in all async functions, like:

```suggestion
              Focus only on the modified code and provide specific, actionable recommendations.", env.OPEN_AI_TOKEN) }}
```

2024-12-23 10:24 UTC, MishaKav commented on docs/downloads/automation-library/integrations/askAI/askAI_document.cm
> +              Format the output in clear, concise bullet points or paragraphs.", env.OPEN_AI_TOKEN) | encode }}
```suggestion
              Format the output in clear, concise bullet points or paragraphs.", env.OPEN_AI_TOKEN) }}
```

2024-12-23 10:27 UTC, MishaKav requested changes

2024-12-23 10:27 UTC, MishaKav commented on docs/downloads/automation-library/integrations/askAI/askAI_CR.cm
> +  ask_ai_review:
remove the `encode`

2024-12-23 10:27 UTC, MishaKav commented on docs/downloads/automation-library/integrations/askAI/askAI_tests.cm
> +  ask_ai_tests:
remove the `encode`

2024-12-23 10:27 UTC, MishaKav commented on docs/downloads/automation-library/integrations/askAI/askAI_summarize.cm
> +  ask_ai_summarize:
remove the `encode`

2024-12-23 11:07 UTC, MishaKav approved these changes
Lg

2024-12-23 11:50 UTC, MishaKav approved these changes
Looks good.

In general, I don't like the `# 🧪 Test Suggestions 🧪`, because it make the title too big.
I think we may change it to something more elegant. Bold or ###

2024-12-24 14:45 UTC, merged